export const USER_LOGGING_IN = 'USER_LOGGING_IN';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';

export const FETCH_OAUTH_FETCHED = "FETCH_OAUTH_FETCHED"
export const FETCH_OAUTH_REJECTED = "FETCH_OAUTH_REJECTED"
export const FETCH_OAUTH_FETCHING = "FETCH_OAUTH_FETCHING"
export const FETCH_OAUTH_EXPIRED = "FETCH_OAUTH_EXPIRED"