export const USER_LOGGING_IN = 'USER_LOGGING_IN';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const FETCH_OAUTH_FETCHED = "FETCH_OAUTH_FETCHED"
export const FETCH_OAUTH_LOGOUT = "FETCH_OAUTH_LOGOUT"
export const FETCH_OAUTH_REJECTED = "FETCH_OAUTH_REJECTED"
export const FETCH_OAUTH_FETCHING = "FETCH_OAUTH_FETCHING"
export const FETCH_OAUTH_EXPIRED = "FETCH_OAUTH_EXPIRED"

export const FETCH_USER = 'FETCH_USER'
export const FETCH_SINGLE_USER = 'FETCH_SINGLE_USER'
export const REJECT_SINGLE_USER = 'REJECT_SINGLE_USER'
export const FETCHING_USER = 'FETCHING_USER'
export const REJECT_USER = 'REJECT_USER'
export const FETCH_USER_ITEMS = 'FETCH_USER_ITEMS'
export const REJECT_USER_ITEMS = 'REJECT_USER_ITEMS'

export const FETCH_USER_ROLE = 'FETCH_USER_ROLE'
export const FETCHING_USER_ROLE = 'FETCHING_USER_ROLE'

export const FETCH_KIT_CONTROLLER = 'FETCH_KIT_CONTROLLER'
export const FETCHING_KIT_CONTROLLER = 'FETCHING_KIT_CONTROLLER'
export const REJECT_KIT_CONTROLLER = 'REJECT_KIT_CONTROLLER'

export const FETCHING_KIT_TYPE = 'FETCHING_KIT_TYPE'
export const FETCH_KIT_TYPE = 'FETCH_KIT_TYPE'
export const REJECT_KIT_TYPE = 'REJECT_KIT_TYPE'

export const FETCHING_KIT_ITEM = 'FETCHING_KIT_ITEM'
export const FETCH_KIT_ITEM = 'FETCH_KIT_ITEM'
export const REJECT_KIT_ITEM = 'REJECT_KIT_ITEM'
export const FETCH_KIT_ITEM_FOR_USER = 'FETCH_KIT_ITEM_FOR_USER'
